# Generated by Django 4.2.6 on 2023-10-27 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coverimg',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='cover_images'),
        ),
    ]
