# Generated by Django 4.2.6 on 2023-10-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profile_coverimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='coverimg',
            field=models.ImageField(default='cover-photo-black.jpg', upload_to='cover_images'),
        ),
    ]
